baseURL = 'https://aysimamedikal.netlify.app/'
languageCode = 'tr-TR'
title = 'Aysima Medikal'
theme = 'simple-shop'
enableEmoji = true
contentDir = 'content'
[outputs]
  home = ['HTML', 'RSS', 'JSON']
[params]
  collage = [
  "/images/uploads/collage-1.jpg",
  "/images/uploads/collage-2.jpg",
  "/images/uploads/collage-3.jpg",
  "/images/uploads/collage-4.jpg",
  "/images/uploads/collage-5.jpg",
  "/images/uploads/collage-6.jpg",
  "/images/uploads/collage-7.jpg",
  "/images/uploads/collage-8.jpg",
  ]
  # snipcart features will not work without an api key
  # see https://docs.snipcart.com/v3/dashboard/account-configuration#3-api-keys
  # snipcart_key = ""
  favicon= "/images/favicon.png"

