baseURL = 'https://aysimamedikal.netlify.app/'
languageCode = 'tr-TR'
title = 'Aysima Medikal'
theme = 'simple-shop'
enableEmoji = true
contentDir = 'content'
[outputs]
  home = ['HTML', 'RSS', 'JSON']
[params]
  instagram = "aysimamedikal"
  header = "Aysima Medikal"
  description = "Antalya'nın güvenilir medikal ürün katalogu"
  products_title = "Envanterimiz"
  reviews_title = "İncelemelerimiz"
  not_found = "Üzgünüz, bu kategoride henüz ürünümüz bulunmamaktadır."
  categories = [
    "İlaç",
    "Teçhizat",
    "Tedarik"
  ]
  collage = [
  "/images/uploads/collage-1.png",
  "/images/uploads/collage-2.png",
  "/images/uploads/collage-3.png",
  "/images/uploads/collage-4.png",
  "/images/uploads/collage-5.png",
  "/images/uploads/collage-6.png",
  "/images/uploads/collage-7.png",
  "/images/uploads/collage-8.png",
  ]
  # snipcart features will not work without an api key
  # see https://docs.snipcart.com/v3/dashboard/account-configuration#3-api-keys
  # snipcart_key = ""
  favicon= "/images/favicon.png"

