baseURL = 'https://teriyakigod.github.io/medical-store-website/'
languageCode = 'tr-TR'
title = 'Aysima Medikal'
theme = 'simple-shop'
enableEmoji = true
contentDir = 'content/products'
[outputs]
  home = ['HTML', 'RSS', 'JSON']
[params]
  instagram = "aysimamedikal"
  header = "Aysima Medikal"
  description = "Antalya'nın güvenilir medikal ürün katalogu"
  products_title = "Envanterimiz"
  reviews_title = "İncelemelerimiz"
  not_found = "Üzgünüz, bu kategoride henüz ürünümüz bulunmamaktadır."
  categories = [
    "İlaç",
    "Teçhizat",
    "Tedarik"
  ]
  collage = [
    "/images/collage-1.jpg",
    "/images/collage-2.jpg",
    "/images/collage-3.jpg",
    "/images/collage-8.jpg",
    "/images/collage-7.jpg",
    "/images/collage-4.jpg",
    "/images/collage-5.jpg",
    "/images/collage-6.jpg"
  ]
  # snipcart features will not work without an api key
  # see https://docs.snipcart.com/v3/dashboard/account-configuration#3-api-keys
  snipcart_key = ""
  favicon= "/images/favicon.png"

