backend:
  name: github
  repo: TeriyakiGod/medical-store-website
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Category", name: "categories", widget: "select", options: ["İlaç", "Teçhizat", "Tedarik"] }
  - name: "reviews"
    label: "Reviews"
    folder: "content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Customer Name", name: "author", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Comment", name: "comment", widget: "text" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/contact.md"
        name: "contact"
        label: "Contact"
        fields:
          - { label: "Type", name: "type", widget: "hidden", default: "contact" }
          - { label: "Title", name: "title", widget: "string", default: "İletişim" }
          - { label: "Address", name: "address", widget: "text", required: false }
          - { label: "Phone", name: "phone", widget: "string", required: false }
          - { label: "Email", name: "email", widget: "string", required: false }
          - { label: "WhatsApp", name: "whatsapp", widget: "string", required: false }
          - { label: "Map Embed (HTML)", name: "map_embed", widget: "text", required: false, hint: "Google Maps embed iframe HTML" }
          - { label: "Body", name: "body", widget: "markdown" }