backend:
  name: github
  repo: TeriyakiGod/medical-store-website
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Category", name: "categories", widget: "select", options: ["İlaç", "Teçhizat", "Tedarik"] }
  - name: "reviews"
    label: "Reviews"
    folder: "content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Customer Name", name: "author", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Comment", name: "comment", widget: "text" }